# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: install node@14.0.0
          command: |
            set +e         
            touch $BASH_ENV    
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v14.0.0' >> $BASH_ENV
            echo 'nvm alias default v14.0.0' >> $BASH_ENV
      - run:
          name: verify node version
          command: node --version

      - run: npm run pbuild

      - run:
          command: |
            docker build -t uvarajat.azurecr.io/myapp:1.0 .
      - run:
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS uvarajat.azurecr.io
      - run:
          command: |
            docker push uvarajat.azurecr.io/myapp:1.0